module.exports = {
  "drugs": [
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "早产儿",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 20,
      "base_dose_high": 20,
      "frequency": "q12h",
      "max_daily_dose": 0,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "PMA 26-30周且eCrCL > 50",
      "special_warning": "有肾损伤体征的<3月龄患儿无推荐剂量，禁止计算",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表3",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "早产儿",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 20,
      "base_dose_high": 20,
      "frequency": "q8h",
      "max_daily_dose": 0,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "PMA 31-44周且eCrCL > 50",
      "special_warning": "有肾损伤体征的<3月龄患儿无推荐剂量，禁止计算",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表3",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "早产儿",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 30,
      "base_dose_high": 30,
      "frequency": "q8h",
      "max_daily_dose": 0,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "PMA 45 ~ <53周且eCrCL > 50",
      "special_warning": "有肾损伤体征的<3月龄患儿无推荐剂量，禁止计算",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表3",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "足月儿",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 20,
      "base_dose_high": 20,
      "frequency": "q8h",
      "max_daily_dose": 0,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "出生-28天且eCrCL > 50",
      "special_warning": "有肾损伤体征的<3月龄患儿无推荐剂量，禁止计算",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表6",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "足月儿",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 30,
      "base_dose_high": 30,
      "frequency": "q8h",
      "max_daily_dose": 0,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "29天-3月龄且eCrCL > 50",
      "special_warning": "有肾损伤体征的<3月龄患儿无推荐剂量，禁止计算",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表6",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 40,
      "base_dose_high": 40,
      "frequency": "q8h",
      "max_daily_dose": 6000,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "3-6月龄且eCrCL > 50",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表2",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 20,
      "base_dose_high": 20,
      "frequency": "q8h",
      "max_daily_dose": 3000,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "3-6月龄且eCrCL 31-50",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 15,
      "base_dose_high": 15,
      "frequency": "q12h",
      "max_daily_dose": 1500,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "3-6月龄且eCrCL 16-30",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 50,
      "base_dose_high": 50,
      "frequency": "q8h",
      "max_daily_dose": 6000,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "6月龄-2岁且eCrCL > 50",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表2",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 25,
      "base_dose_high": 25,
      "frequency": "q8h",
      "max_daily_dose": 3000,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "6月龄-2岁且eCrCL 31-50",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 18.75,
      "base_dose_high": 18.75,
      "frequency": "q12h",
      "max_daily_dose": 1500,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "6月龄-2岁且eCrCL 16-30",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 50,
      "base_dose_high": 50,
      "frequency": "q8h",
      "max_daily_dose": 6000,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "2-18岁且eCrCL > 50",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表2",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 25,
      "base_dose_high": 25,
      "frequency": "q8h",
      "max_daily_dose": 3000,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "2-18岁且eCrCL 31-50",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 18.75,
      "base_dose_high": 18.75,
      "frequency": "q12h",
      "max_daily_dose": 1500,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "2-18岁且eCrCL 16-30",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 18.75,
      "base_dose_high": 18.75,
      "frequency": "q24h",
      "max_daily_dose": 750,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "2-18岁且eCrCL 6-15",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 18.75,
      "base_dose_high": 18.75,
      "frequency": "q48h",
      "max_daily_dose": 750,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "2-18岁且ESRD",
      "special_warning": "在血液透析当日，应在血液透析完成后给予本品",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "早产儿",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 0,
      "base_dose_high": 0,
      "frequency": "禁止计算",
      "max_daily_dose": 0,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "早产儿且eCrCL <= 50",
      "special_warning": "根据官方说明书，现有临床数据不足以推荐 3 月龄以下伴有肾功能损伤儿童患者的给药方案。请进行人工医学判断。",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书/剂量卡",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "足月儿",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 0,
      "base_dose_high": 0,
      "frequency": "禁止计算",
      "max_daily_dose": 0,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "足月儿<3月龄且eCrCL <= 50",
      "special_warning": "根据官方说明书，现有临床数据不足以推荐 3 月龄以下伴有肾功能损伤儿童患者的给药方案。请进行人工医学判断。",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书/剂量卡",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 0,
      "base_dose_high": 0,
      "frequency": "禁止计算",
      "max_daily_dose": 0,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "3-6月龄且eCrCL < 16",
      "special_warning": "根据官方说明书，现有临床数据不足以推荐 3 月龄至 2 岁之间伴有重度肾功能损伤（eCrCL < 16 mL/min/1.73m²）或进行透析患儿的给药方案。请进行人工医学判断。",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书/剂量卡",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "儿童",
      "weight_range": "0.5-80kg",
      "dose_unit": "mg/kg",
      "base_dose_low": 0,
      "base_dose_high": 0,
      "frequency": "禁止计算",
      "max_daily_dose": 0,
      "icu_supported": true,
      "icu_rule": "ICU重症患儿建议每日监测eCrCL并维持液体平衡",
      "renal_supported": true,
      "renal_rule": "6月龄-2岁且eCrCL < 16",
      "special_warning": "根据官方说明书，现有临床数据不足以推荐 3 月龄至 2 岁之间伴有重度肾功能损伤（eCrCL < 16 mL/min/1.73m²）或进行透析患儿的给药方案。请进行人工医学判断。",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书/剂量卡",
      "reviewer": "医学事务部",
      "review_date": "2026-07-07"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "成人",
      "weight_range": "不限",
      "dose_unit": "mg",
      "base_dose_low": 2000,
      "base_dose_high": 0,
      "frequency": "q8h",
      "max_daily_dose": 6000,
      "icu_supported": true,
      "icu_rule": "重症监测清除率",
      "renal_supported": true,
      "renal_rule": "成人且eCrCL > 50",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表2/表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-10"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "成人",
      "weight_range": "不限",
      "dose_unit": "mg",
      "base_dose_low": 1000,
      "base_dose_high": 0,
      "frequency": "q8h",
      "max_daily_dose": 3000,
      "icu_supported": true,
      "icu_rule": "重症监测清除率",
      "renal_supported": true,
      "renal_rule": "成人且eCrCL 31-50",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表2/表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-10"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "成人",
      "weight_range": "不限",
      "dose_unit": "mg",
      "base_dose_low": 750,
      "base_dose_high": 0,
      "frequency": "q12h",
      "max_daily_dose": 1500,
      "icu_supported": true,
      "icu_rule": "重症监测清除率",
      "renal_supported": true,
      "renal_rule": "成人且eCrCL 16-30",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表2/表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-10"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "成人",
      "weight_range": "不限",
      "dose_unit": "mg",
      "base_dose_low": 750,
      "base_dose_high": 0,
      "frequency": "q24h",
      "max_daily_dose": 750,
      "icu_supported": true,
      "icu_rule": "重症监测清除率",
      "renal_supported": true,
      "renal_rule": "成人且eCrCL 6-15",
      "special_warning": "无特别警告",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表2/表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-10"
    },
    {
      "drug_id": "CAZ_AVI",
      "drug_name": "思福妥",
      "generic_name": "头孢他啶阿维巴坦",
      "population": "成人",
      "weight_range": "不限",
      "dose_unit": "mg",
      "base_dose_low": 750,
      "base_dose_high": 0,
      "frequency": "q48h",
      "max_daily_dose": 750,
      "icu_supported": true,
      "icu_rule": "重症监测清除率",
      "renal_supported": true,
      "renal_rule": "成人且ESRD",
      "special_warning": "在血液透析当日，应在血液透析完成后给予本品",
      "source_document": "说明书",
      "source_version": "20250416",
      "source_page": "说明书表2/表5",
      "reviewer": "医学事务部",
      "review_date": "2026-07-10"
    }
  ],
  "renal": [
    {
      "药品": "思福妥",
      "肾功能等级": "Normal",
      "调整方式": "不调整",
      "调整系数": 1,
      "给药间隔": "q8h",
      "来源": "说明书 Page 4",
      "审核状态": "已审核"
    },
    {
      "药品": "思福妥",
      "肾功能等级": "Moderate",
      "调整方式": "剂量调整",
      "调整系数": 0.5,
      "给药间隔": "q8h",
      "来源": "说明书 Page 5",
      "审核状态": "已审核"
    },
    {
      "药品": "思福妥",
      "肾功能等级": "Severe",
      "调整方式": "剂量调整且给药间隔延长",
      "调整系数": 0.375,
      "给药间隔": "q12h",
      "来源": "说明书 Page 5",
      "审核状态": "已审核"
    },
    {
      "药品": "思福妥",
      "肾功能等级": "Critical",
      "调整方式": "剂量调整且给药间隔延长",
      "调整系数": 0.375,
      "给药间隔": "q24h",
      "来源": "说明书 Page 5",
      "审核状态": "已审核"
    },
    {
      "药品": "思福妥",
      "肾功能等级": "ESRD",
      "调整方式": "剂量调整且给药间隔延长",
      "调整系数": 0.375,
      "给药间隔": "q48h",
      "来源": "说明书 Page 5",
      "审核状态": "已审核"
    }
  ],
  "compiledAt": "2026-07-09T17:51:06.576Z"
};